spring:
  datasource:
    # url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:postgresql://localhost:5432/repertapp
    username: repertapp
    password: teste_repertapp
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: update # create-drop / update
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.H2Dialect
    #     dialect: org.hibernate.dialect.postgreSQLDialect
    #     format_sql: true
    #     id:
    #       new_generator_mappings: false

server:
   port: 8080 # This is the default port anyway, but you can change it here
   error:
    include-stacktrace: ON_PARAM

security:
  jwt:
    token:
      secret-key: b2b12dae-50f3-4413-a9c6-32a329b49f66
      expire-length: 86400000 # 24 * 60 * 60 * 1000 = 24 hours duration by default: 24 hours * 60 minutes * 60 seconds * 1000 miliseconds
  